refresh_seed_url:
  cron: "*/3 * * * *" # Every 1 minutes
  class: "CrawlPipeline::SeedUrlWorker"

crawl_web_link:
  cron: "*/5 * * * *" # Every 5 minutes
  class: "CrawlPipeline::StartCrawlWorkflowWorker"
