refresh_seed_url:
  cron: "*/15 * * * *" # Every 15 minutes
  class: "CrawlPipeline::SeedUrlWorker"

crawl_web_link:
  cron: "* * * * *" # Every 1 minutes
  class: "CrawlPipeline::StartCrawlWorkflowWorker"

extract_web_content:
  cron: "* * * * *" # Every 5 minutes
  class: "ExtractorPipeline::StartExtractionWorkflowWorker"
