refresh_seed_url:
  cron: "*/15 * * * *" # Every 15 minutes
  class: "SeedUrlWorker"

crawl_web_link:
  cron: "* * * * *" # Every 1 minutes
  class: "CrawlPipelineWorker"

extract_web_content:
  cron: "* * * * *" # Every 5 minutes
  class: "ExtractorPipelineWorker"
